version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"  # Default value, can be overridden by CodeBuild environment variables
    ECR_REPOSITORY_NAME: "lambda-glue-job-trigger"  # Default value, can be overridden by CodeBuild environment variables
    AWS_ACCOUNT_ID: "554415012351"  # Default value, can be overridden by CodeBuild environment variables

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $ECR_REPOSITORY_NAME .
      - docker tag $ECR_REPOSITORY_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:latest

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:latest

artifacts:
  files: 
    - 'lambda_handler.py'
    - 'Dockerfile'
    - 'buildspec.yml'

cache:
  paths:
    - '/var/cache/apt/archives/**/*'
